apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: server-accesslog-stackdriver
  namespace: istio-system
spec:
  severity: '"Info"'
  timestamp: request.time
  variables:
    source_ip: source.ip | ip("0.0.0.0")
    destination_service_name: destination.service.name | "unknown"
    destination_port: destination.port | 0
    request_operation: request.method | "unknown"
    request_protocol: context.protocol | "unknown"
    api_version: api.version | "unknown"
    api_name: api.service | "unknown"
    response_code: response.code | 0
    service_authentication_policy: '"NONE"'
    source_workload_namespace: source.workload.namespace | "unknown"
    source_workload_name: source.workload.name | "unknown"
    source_owner: source.owner | "unknown"
    destination_workload_namespace: destination.workload.namespace | "unknown"
    destination_workload_name: destination.workload.name | "unknown"
    destination_owner: destination.owner | "unknown"
    response_size: response.size | 0
    request_size: request.size | 0
    request_latency: response.duration | "0ms"
    connection_received_bytes: connection.received.bytes | 0
    connection_sent_bytes: connection.sent.bytes | 0
  monitored_resource_type: '"k8s_container"'
  monitoredResourceDimensions:
    project_id: '""'
    cluster_name: '""'
    namespace_name: destination.namespace | "unknown"
    location: '""'
    container_name: destination.container.name | "unknown"
    pod_name: destination.name | "unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: stackdriver
metadata:
  name: log-handler
  namespace: istio-system
spec:
  pushInterval: 10s
  # Describes how to map Istio logs into Stackdriver.
  logInfo:
    server-accesslog-stackdriver.logentry.istio-system:
      labelNames:
      - source_ip
      - destination_service_name
      - destination_port
      - request_operation
      - request_protocol
      - api_version
      - api_name
      - response_code
      - service_authentication_policy
      - source_workload_namespace
      - source_workload_name
      - source_owner
      - destination_workload_namespace
      - destination_workload_name
      - destination_owner
      - response_size
      - request_size
      - request_latency
      - connection_received_bytes
      - connection_sent_bytes
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: stackdriver-log
  namespace: istio-system
spec:
  match: context.reporter.local
  actions:
  - handler: log-handler.stackdriver
    instances:
    - server-accesslog-stackdriver.logentry
