apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-to-stackdriver
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-to-stackdriver
  template:
    metadata:
      name: zipkin-to-stackdriver
      labels:
        app: zipkin-to-stackdriver
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: zipkin-to-stackdriver
        image: gcr.io/stackdriver-trace-docker/zipkin-collector
        imagePullPolicy: IfNotPresent
        ports:
        - name: zipkin
          containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: istio-system
spec:
  ports:
  - name: zipkin
    port: 9411
  selector:
    app: zipkin-to-stackdriver
---
# apiVersion: config.istio.io/v1alpha2
# kind: EgressRule
# metadata:
#   name: googleapis
#   namespace: default
# spec:
#   destination:
#     service: "*.googleapis.com"
#   ports:
#     - port: 443
#        protocol: https
#---
